version: '3.9'
services:
  node-app:
    restart: always
    image: 10.63.20.108/nextgen/mddpnodebackend:v4
    container_name: mddpnodebackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/mddpdb_test

  mongo:
    image: mongo
    restart: always
    image: 10.63.20.108/nextgen/mongodb:v1
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: mddpdb_test
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    image: 10.63.20.108/nextgen/mongodbui:v1
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
      ME_CONFIG_BASICAUTH: false
volumes:
  mongo_data:
    driver: local